site_name: Pack 1158
pages:
  - Home: index.md
  - Join:
    - Join Pack 1158: join.md
#    - Join Scouting Night: events/join-scouting-night.md
#  - Events:
#    - Bike Hike: events/bike-hike.md
#    - Bottle Rocket Derby: events/soda-bottle-rocket-derby.md
#    - Day/Twilight Camp: events/passport-to-adventure.md
#    - Fall Campout: events/campout-fall-2019.md
#    - Independence Day Parade: events/independence-day-parade.md
#    - Join Scouting Night: events/join-scouting-night.md
#    - P-Nats Scout Night: events/potomac-nationals-scout-night.md
#    - Water Mine: events/water-mine-back-to-school-blast.md
  - Resources:
    - Flag Ceremony: resources/flag-ceremony.md
    - Forms: resources/forms.md
    - Handbook: resources/handbook.md
  - Outdoors:
    - Outdoors: outdoors/outdoors.md
    - Hiking: outdoors/hiking.md
    - Packing List: resources/camp-packing-list.md
